### ISSUE TITLE
Instagram updated login error

### ISSUE THREAD

**Issue by rfdiego** [niuware/instpector#12]
I think that yesterday the instagram api have changed and instpector is not loging and stop working...
`
GET RequestException: HTTPSConnectionPool(host='www.instagram.com', port=443): Read timed out.
Traceback (most recent call last):
  File "T:\instagram followwre\sorteios\examples\follow_profile.py", line 78, in <module>
    if not instpector.login(user=USUARIO, password=SENHA):
  File "T:\instagram followwre\sorteios\instpector\instpector.py", line 25, in login
    self._auth.login()
  File "T:\instagram followwre\sorteios\instpector\apis\instagram\authenticate.py", line 20, in login
    self._login_prepare()
  File "T:\instagram followwre\sorteios\instpector\apis\instagram\authenticate.py", line 74, in _login_prepare
    app_id, ajax_id = self._lookup_headers()
  File "T:\instagram followwre\sorteios\instpector\apis\instagram\authenticate.py", line 60, in _lookup_headers
    app_id = get_app_id(js_lib.text)
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by rfdiego** [comment]
Sorry guys.. the instagram was unvailable but now its ok!
